
version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_container
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:admin@mongodb:27017

volumes:
  mongodb_data:
